spring:
  application.name: swagger-coffee-consumer-simple
  # remove::start[]
  cloud.stream.bindings.input.destination: verifications
  # remove::end[]
server.port: ${PORT:8081}
logging:
  level:
    org.springframework.cloud: debug

coffee:
  producer:
    url: http://localhost
    port: 8080